---
# Install openstack packages

- name: unwanted packages are removed
  package:
    name: "{{ openstack_packages_remove }}"
    state: absent
  become: true
  when: openstack_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ openstack_packages_repos }}"
    state: "{{ openstack_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ openstack_packages_prereq }}"
    state: "{{ openstack_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ openstack_packages_install }}"
    state: "{{ openstack_packages_state }}"
  become: true
